[package]
name = "snowden"
version = "0.1.0"
authors = ["Ujjwal Sharma <ryzokuken@disroot.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpgme = "0.9"
xdg = "2.2"
toml = "0.5"
git2 = "0.13"
clap = "2.33"
